### PR TITLE
Allow video popup dialog to fetch from backend url

### PR DESCRIPTION
**Pull request by kchenturtles**

### CODE REVIEW

**Review by am5815 — CHANGES_REQUESTED** [review]
I have a feeling that you have swapped the audio available so that it is showing the listen option only on the articles that actually dont have any audio available.

**Comment by am5815** [comment]
Ok Im not sure what it is, but the playing audio functionality isn't working. IT is working on prod.

**Comment by kchenturtles** [comment]
For me sometimes audio worked and sometimes it didn't, but I thought that might be an issue with the API

**Comment by am5815** [comment]
Ok so same issue, text to speech isn't working. You can test this by playing the mindfulness and meditation article on localhost vs playing it on cycminds.org. It works on cycminds.org and doesn't in local.

**Comment by kchenturtles** [comment]
> Ok so same issue, text to speech isn't working. You can test this by playing the mindfulness and meditation article on localhost vs playing it on cycminds.org. It works on cycminds.org and doesn't in local.

Should be fixed now

**Review by am5815 — APPROVED** [review]
looks good :)

**Pull request merged**
